language: node_js
node_js: node
install:
  - npm install
  - npm link
services:
  - docker
env:
  - TESTFOLDER=test/cli-commands
  - TESTFOLDER=test/deployed-contract
  - TESTFOLDER=test/deployer
  - TESTFOLDER=test/logger-service
  - TESTFOLDER=test/logs-store
  - TESTFOLDER=test/testContracts
  - TESTFOLDER=test/utils
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage
