language:
  - node_js:
install:
  - npm install
  - npm link
services:
  - docker
env:
  - TESTFOLDER=test/cli-commands/**/*.js
  - TESTFOLDER=test/deployed-contract/*.js
  - TESTFOLDER=test/deployer/**/*.js
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage
