language:
  - node_js:
install:
  - npm install
  - npm link
services:
  - docker
env:
  - TESTFOLDER=test/cli-commands/*.js
  - TESTFOLDER=test/deployed-contract/*.js
  - TESTFOLDER=test/deployer/*.js
  - TESTFOLDER=test/logger-service/*.js
  - TESTFOLDER=test/logs-store/*.js
  - TESTFOLDER=test/testContracts/*.js
  - TESTFOLDER=test/utils/*.js
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage
